{{/*
This template ensures Redis and PostgreSQL subcharts use the same passwords as Coolify.
We do this by setting the passwords in the subchart auth configurations.
*/}}
{{- include "coolify.sync.redisPassword" . }}
{{- $dbPassword := include "coolify.secret.dbPassword" . }}
{{- $_ := set .Values.postgresql.auth "password" $dbPassword }}
---
# This comment ensures the template is processed but doesn't output anything
