{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "coolify.coolifyApp.fullname" . }}-ingress'
  namespace: {{ include "coolify.namespace" . }}
  labels:
    {{ include "coolify.labels" (merge (dict "componentName" "core") .) | nindent 4 }}
  annotations:
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{ if .Values.ingress.className }}
    ingressClassName: {{ .Values.ingress.className }}
  {{ end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{ range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "coolify.coolifyApp.serviceName" $ }}
                port:
                  number: {{ $.Values.coolifyApp.service.port }}
          {{ end }}
    {{- end }}
  {{ if .Values.ingress.tls }}
    tls:
      {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{ end }}
{{ end }}
