{{ if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coolify.postgresql.fullname" . }}
  namespace: {{ include "coolify.namespace" . }}
  labels:
    {{ include "coolify.labels" (merge (dict "componentName" "postgresql") .) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
  type: Opaque
data:
  postgres-password: {{ include "coolify.postgresql.adminPassword" . | b64enc | quote }}
  password: {{ include "coolify.postgresql.userPassword" . | b64enc | quote }}
{{ end }}
