{{ if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coolify.redis.fullname" . }}
  namespace: {{ include "coolify.namespace" . }}
  labels:
    {{ include "coolify.labels" (merge (dict "componentName" "redis") .) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  redis-password: {{ include "coolify.redis.password" . | b64enc | quote }}
{{ end }}
