apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coolify.secret.name" . }}
  namespace: {{ include "coolify.namespace" . }}
  labels:
    {{ include "coolify.labels" (merge (dict "componentName" "secrets") .) | nindent 4 }}
type: Opaque
data:
  APP_ID: {{ include "coolify.secret.appId" . | b64enc | quote }}
  APP_KEY: {{ include "coolify.secret.appKey" . | b64enc | quote }}

  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | default "coolify" | b64enc | quote }}
  DB_PASSWORD: {{ include "coolify.secret.dbPassword" . | b64enc | quote }}

  REDIS_PASSWORD: {{ include "coolify.secret.redisPassword" . | b64enc | quote }}

  PUSHER_APP_ID: {{ include "coolify.secret.pusherAppId" . | b64enc | quote }}
  PUSHER_APP_KEY: {{ include "coolify.secret.pusherAppKey" . | b64enc | quote }}
  PUSHER_APP_SECRET: {{ include "coolify.secret.pusherAppSecret" . | b64enc | quote }}

  ROOT_USERNAME: {{ .Values.secrets.ROOT_USERNAME | b64enc | quote }}
  ROOT_USER_EMAIL: {{ .Values.secrets.ROOT_USER_EMAIL | b64enc | quote }}
  ROOT_USER_PASSWORD: {{ include "coolify.secret.rootUserPassword" . | b64enc | quote }}
